<template>
    <section class="ai-page">
        <div class="ai-shell">
            <header class="ai-header">
                <span class="ai-eyebrow">Assistant</span>
                <h1>AI Insights</h1>
                <p>Summaries, answers, and reorder suggestions for {{ currentStoreLabel }}.</p>
            </header>

            <div v-if="!storeContext.currentStoreId" class="ai-state">Select a store to use AI Insights.</div>

            <div v-else-if="!hasAnyAccess" class="ai-state">Your role does not have access to AI Insights for this store.</div>

            <div v-else-if="!aiConfigured" class="ai-state ai-state--setup">
                <mdicon name="robot-confused-outline" size="28" />
                <h2>AI isn't set up yet</h2>
                <p>Add an AI provider and API key to unlock summaries, chat, and reorder suggestions.</p>
                <RouterLink v-if="canConfigure" class="ai-summary-btn" :to="`/stores/${storeContext.currentStoreId}/settings?section=ai`">
                    Configure AI
                </RouterLink>
                <p v-else class="ai-state-note">Ask an owner or admin to configure AI in Store Settings.</p>
            </div>

            <template v-else>
                <!-- ── Daily summary ── -->
                <div v-if="canUseAiSummary" class="ai-summary-card">
                    <div class="ai-summary-head">
                        <div class="ai-summary-title">
                            <span class="ai-summary-icon"><mdicon name="robot-happy-outline" size="18" /></span>
                            <div>
                                <h2>AI daily summary</h2>
                                <p>Plain-language recap of your last complete day.</p>
                            </div>
                        </div>
                        <button type="button" class="ai-summary-btn" :disabled="isGeneratingSummary" @click="generateSummary">
                            <mdicon :name="isGeneratingSummary ? 'loading' : 'creation'" size="15" :class="{ 'ai-spin': isGeneratingSummary }" />
                            {{ isGeneratingSummary ? 'Generating…' : aiSummary ? 'Regenerate' : 'Generate summary' }}
                        </button>
                    </div>
                    <div v-if="aiSummaryError" class="ai-summary-error">{{ aiSummaryError }}</div>
                    <div v-if="isGeneratingSummary && !aiSummary" class="ai-summary-loading">Analyzing your sales, margins, and stock…</div>
                    <div v-else-if="aiSummary" class="ai-summary-body">
                        <div class="ai-summary-text" v-html="renderedSummary"></div>
                        <p class="ai-summary-meta">Generated by {{ aiSummaryModel }} · for {{ aiSummaryDate }}</p>
                    </div>
                    <p v-else class="ai-summary-empty">Click “Generate summary” to get an AI recap of yesterday’s performance.</p>
                </div>

                <!-- ── Ask your data ── -->
                <div v-if="canUseAiSummary" class="ai-chat-card">
                    <div class="ai-summary-head">
                        <div class="ai-summary-title">
                            <span class="ai-summary-icon"><mdicon name="chat-question-outline" size="18" /></span>
                            <div>
                                <h2>Ask your data</h2>
                                <p>Ask about sales, products, margins, payments, or stock.</p>
                            </div>
                        </div>
                        <button v-if="chatMessages.length" type="button" class="ai-chat-clear" :disabled="isChatting" @click="clearChat">Clear</button>
                    </div>

                    <div v-if="chatMessages.length" ref="chatScrollRef" class="ai-chat-log">
                        <div v-for="(m, i) in chatMessages" :key="i" class="ai-chat-msg" :class="`ai-chat-msg--${m.role}`">
                            <div v-if="m.role === 'assistant'" class="ai-chat-bubble ai-summary-text" v-html="renderMarkdownLite(m.content)"></div>
                            <div v-else class="ai-chat-bubble">{{ m.content }}</div>
                        </div>
                        <div v-if="isChatting" class="ai-chat-msg ai-chat-msg--assistant">
                            <div class="ai-chat-bubble ai-chat-typing">Thinking…</div>
                        </div>
                    </div>
                    <div v-else class="ai-chat-suggestions">
                        <button v-for="s in chatSuggestions" :key="s" type="button" class="ai-chat-chip" :disabled="isChatting" @click="askSuggestion(s)">
                            {{ s }}
                        </button>
                    </div>

                    <div v-if="chatError" class="ai-summary-error">{{ chatError }}</div>

                    <form class="ai-chat-input" @submit.prevent="sendChat">
                        <input v-model="chatInput" type="text" placeholder="e.g. How many Cheese Bombs did I sell last month?" :disabled="isChatting" />
                        <button type="submit" class="ai-summary-btn" :disabled="isChatting || !chatInput.trim()">
                            <mdicon :name="isChatting ? 'loading' : 'send'" size="15" :class="{ 'ai-spin': isChatting }" />
                            Send
                        </button>
                    </form>
                </div>

                <!-- ── Reorder suggestions ── -->
                <div v-if="canUseReorder" class="ai-summary-card">
                    <div class="ai-summary-head">
                        <div class="ai-summary-title">
                            <span class="ai-summary-icon"><mdicon name="cart-arrow-down" size="18" /></span>
                            <div>
                                <h2>Reorder suggestions</h2>
                                <p>What's running low and how much to order, based on the last 30 days.</p>
                            </div>
                        </div>
                        <button type="button" class="ai-summary-btn" :disabled="isReordering" @click="generateReorder">
                            <mdicon :name="isReordering ? 'loading' : 'creation'" size="15" :class="{ 'ai-spin': isReordering }" />
                            {{ isReordering ? 'Analyzing…' : reorderPlan ? 'Refresh' : 'Generate plan' }}
                        </button>
                    </div>

                    <div v-if="reorderError" class="ai-summary-error">{{ reorderError }}</div>
                    <div v-if="isReordering && !reorderPlan" class="ai-summary-loading">Estimating usage and days of cover…</div>

                    <div v-else-if="reorderPlan" class="ai-summary-body">
                        <p v-if="reorderNarrativeError" class="ai-reorder-note">
                            AI narrative unavailable ({{ reorderNarrativeError }}) — suggestions below are still accurate.
                        </p>
                        <div v-if="reorderNarrative" class="ai-summary-text" v-html="renderMarkdownLite(reorderNarrative)"></div>

                        <p v-if="!reorderPlan.suggestions.length" class="ai-summary-empty">
                            Nothing needs reordering right now — all tracked items have enough cover.
                        </p>
                        <div v-else class="ai-reorder-table-wrap">
                            <table class="ai-reorder-table">
                                <thead>
                                    <tr>
                                        <th>Item</th>
                                        <th class="num">On hand</th>
                                        <th class="num">Used/day</th>
                                        <th class="num">Days left</th>
                                        <th class="num">Order</th>
                                        <th>Supplier</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="s in reorderPlan.suggestions" :key="`${s.itemType}:${s.itemId}`">
                                        <td>{{ s.name }}</td>
                                        <td class="num">{{ s.currentQty }} {{ s.unit }}</td>
                                        <td class="num">{{ s.dailyUsage }}</td>
                                        <td class="num"><span :class="['days-pill', daysClass(s.daysOfCover)]">{{ s.daysOfCover ?? '—' }}</span></td>
                                        <td class="num"><strong>{{ s.suggestedQty }} {{ s.unit }}</strong></td>
                                        <td>{{ s.supplier || '—' }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <p class="ai-summary-meta">
                            Lead time ≈ {{ reorderPlan.leadTimeDays }}d · target cover {{ reorderPlan.targetDaysOfCover }}d · window {{ reorderPlan.window.days }}d
                            <template v-if="reorderModel"> · {{ reorderModel }}</template>
                        </p>
                    </div>
                    <p v-else class="ai-summary-empty">Generate a plan to see what to reorder and how much.</p>
                </div>
            </template>
        </div>
    </section>
</template>

<script setup lang="ts">
import { computed, nextTick, ref } from 'vue';
import { RouterLink } from 'vue-router';
import { useStoreContextStore } from '@/stores/storeContext';
import { renderMarkdownLite } from '@/utils/markdownLite';
import {
    generateDailySummary,
    aiChat,
    generateReorderPlan,
    type AiChatMessage,
    type ReorderPlanResponse,
} from '@/api/ai';

const storeContext = useStoreContextStore();

const currentStoreLabel = computed(() => storeContext.currentStore?.name ?? 'this store');
const role = computed(() => storeContext.currentStore?.role);
const aiConfigured = computed(() => !!storeContext.currentStore?.aiApiKeySet);
const canConfigure = computed(() => role.value === 'OWNER' || role.value === 'ADMIN');
const canUseAiSummary = computed(() => role.value === 'OWNER' || role.value === 'ADMIN');
const canUseReorder = computed(() => role.value === 'OWNER' || role.value === 'ADMIN' || role.value === 'INVENTORY_MANAGER');
const hasAnyAccess = computed(() => canUseAiSummary.value || canUseReorder.value);

// --- Daily summary ---
const aiSummary = ref<string | null>(null);
const aiSummaryModel = ref('');
const aiSummaryDate = ref('');
const aiSummaryError = ref('');
const isGeneratingSummary = ref(false);
const renderedSummary = computed(() => (aiSummary.value ? renderMarkdownLite(aiSummary.value) : ''));

const generateSummary = async () => {
    const storeId = storeContext.currentStoreId;
    if (!storeId || isGeneratingSummary.value) return;
    isGeneratingSummary.value = true;
    aiSummaryError.value = '';
    try {
        const result = await generateDailySummary(storeId);
        aiSummary.value = result.summary;
        aiSummaryModel.value = result.model;
        aiSummaryDate.value = result.data.targetDate;
    } catch (error: any) {
        aiSummaryError.value = error?.body?.error?.message || 'Unable to generate the summary. Please try again.';
    } finally {
        isGeneratingSummary.value = false;
    }
};

// --- Ask your data chat ---
const chatMessages = ref<AiChatMessage[]>([]);
const chatInput = ref('');
const isChatting = ref(false);
const chatError = ref('');
const chatScrollRef = ref<HTMLElement | null>(null);
const chatSuggestions = [
    'How did sales compare to last week?',
    'Top 5 products this month',
    'Which products have the lowest margin?',
    'What needs reordering?',
];

const scrollChatToBottom = () => {
    nextTick(() => {
        if (chatScrollRef.value) chatScrollRef.value.scrollTop = chatScrollRef.value.scrollHeight;
    });
};

const sendMessage = async (text: string) => {
    const storeId = storeContext.currentStoreId;
    const trimmed = text.trim();
    if (!storeId || !trimmed || isChatting.value) return;
    chatError.value = '';
    chatMessages.value.push({ role: 'user', content: trimmed });
    chatInput.value = '';
    isChatting.value = true;
    scrollChatToBottom();
    try {
        const result = await aiChat(storeId, chatMessages.value.slice(-19));
        chatMessages.value.push({ role: 'assistant', content: result.reply });
    } catch (error: any) {
        chatError.value = error?.body?.error?.message || 'Unable to answer that right now. Please try again.';
    } finally {
        isChatting.value = false;
        scrollChatToBottom();
    }
};

const sendChat = () => sendMessage(chatInput.value);
const askSuggestion = (text: string) => sendMessage(text);
const clearChat = () => {
    chatMessages.value = [];
    chatError.value = '';
};

// --- Reorder suggestions ---
const reorderPlan = ref<ReorderPlanResponse['plan'] | null>(null);
const reorderNarrative = ref<string | null>(null);
const reorderNarrativeError = ref<string | null>(null);
const reorderModel = ref<string | null>(null);
const reorderError = ref('');
const isReordering = ref(false);

const daysClass = (days: number | null) => {
    if (days === null || days <= 3) return 'days-pill--crit';
    if (days <= 7) return 'days-pill--warn';
    return 'days-pill--ok';
};

const generateReorder = async () => {
    const storeId = storeContext.currentStoreId;
    if (!storeId || isReordering.value) return;
    isReordering.value = true;
    reorderError.value = '';
    try {
        const result = await generateReorderPlan(storeId);
        reorderPlan.value = result.plan;
        reorderNarrative.value = result.narrative;
        reorderNarrativeError.value = result.narrativeError;
        reorderModel.value = result.model;
    } catch (error: any) {
        reorderError.value = error?.body?.error?.message || 'Unable to build the reorder plan. Please try again.';
    } finally {
        isReordering.value = false;
    }
};
</script>

<style scoped>
.ai-page {
    --c-text: #0f172a;
    --c-muted: #64748b;
    --c-accent: #0d9488;
    --c-accent-dark: #0f766e;
    --c-border: #e2e8f0;
    --c-surface: #ffffff;
    --c-bg: #f8fafc;
    min-height: 100vh;
    padding: 2rem 1.5rem 3rem;
    background: var(--c-bg);
    color: var(--c-text);
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.ai-shell {
    max-width: 1000px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}

.ai-header h1 {
    font-size: 1.6rem;
    font-weight: 700;
    margin: 0.15rem 0 0.25rem;
}

.ai-eyebrow {
    font-size: 0.72rem;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--c-accent);
}

.ai-header p {
    margin: 0;
    color: var(--c-muted);
    font-size: 0.9rem;
}

.ai-state {
    background: var(--c-surface);
    border: 1.5px solid var(--c-border);
    border-radius: 14px;
    padding: 2rem;
    text-align: center;
    color: var(--c-muted);
}

.ai-state--setup {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    color: var(--c-text);
}

.ai-state--setup h2 {
    margin: 0.3rem 0 0;
    font-size: 1.1rem;
}

.ai-state--setup p {
    margin: 0;
    color: var(--c-muted);
    font-size: 0.9rem;
}

.ai-state--setup .ai-summary-btn {
    margin-top: 0.5rem;
    text-decoration: none;
}

.ai-state-note {
    font-size: 0.82rem;
}

/* Cards */
.ai-summary-card,
.ai-chat-card {
    background: var(--c-surface);
    border: 1.5px solid var(--c-border);
    border-radius: 14px;
    padding: 1.25rem 1.4rem;
    box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);
}

.ai-summary-head {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    flex-wrap: wrap;
}

.ai-summary-title {
    display: flex;
    gap: 0.7rem;
    align-items: flex-start;
}

.ai-summary-icon {
    display: grid;
    place-items: center;
    width: 34px;
    height: 34px;
    border-radius: 9px;
    background: rgba(13, 148, 136, 0.1);
    color: var(--c-accent);
    flex-shrink: 0;
}

.ai-summary-title h2 {
    font-size: 1rem;
    font-weight: 700;
    margin: 0;
}

.ai-summary-title p {
    margin: 0.1rem 0 0;
    font-size: 0.8rem;
    color: var(--c-muted);
}

.ai-summary-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.5rem 0.85rem;
    border-radius: 9px;
    border: none;
    background: var(--c-accent);
    color: #fff;
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.12s;
}

.ai-summary-btn:hover:not(:disabled) {
    background: var(--c-accent-dark);
}

.ai-summary-btn:disabled {
    opacity: 0.65;
    cursor: default;
}

.ai-spin {
    animation: ai-spin 0.9s linear infinite;
}

@keyframes ai-spin {
    to {
        transform: rotate(360deg);
    }
}

.ai-summary-loading,
.ai-summary-empty {
    margin: 1rem 0 0;
    font-size: 0.85rem;
    color: var(--c-muted);
}

.ai-summary-error {
    margin: 0.9rem 0 0;
    padding: 0.6rem 0.8rem;
    border-radius: 9px;
    background: #fef2f2;
    color: #b91c1c;
    font-size: 0.82rem;
}

.ai-summary-body {
    margin-top: 1rem;
}

.ai-summary-text {
    font-size: 0.9rem;
    line-height: 1.55;
    color: var(--c-text);
}

.ai-summary-text :deep(p) {
    margin: 0 0 0.55rem;
}

.ai-summary-text :deep(ul) {
    margin: 0 0 0.55rem;
    padding-left: 1.15rem;
}

.ai-summary-text :deep(li) {
    margin: 0.2rem 0;
}

.ai-summary-text :deep(code) {
    background: var(--c-bg);
    padding: 0.05rem 0.3rem;
    border-radius: 5px;
    font-size: 0.85em;
}

.ai-summary-meta {
    margin: 0.5rem 0 0;
    font-size: 0.72rem;
    color: var(--c-muted);
}

/* Chat */
.ai-chat-clear {
    background: none;
    border: 1px solid var(--c-border);
    color: var(--c-muted);
    border-radius: 8px;
    padding: 0.35rem 0.7rem;
    font-size: 0.8rem;
    cursor: pointer;
}

.ai-chat-clear:hover:not(:disabled) {
    color: var(--c-text);
}

.ai-chat-log {
    margin-top: 1rem;
    max-height: 400px;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 0.6rem;
    padding-right: 0.25rem;
}

.ai-chat-msg {
    display: flex;
}

.ai-chat-msg--user {
    justify-content: flex-end;
}

.ai-chat-msg--assistant {
    justify-content: flex-start;
}

.ai-chat-bubble {
    max-width: 85%;
    padding: 0.6rem 0.85rem;
    border-radius: 12px;
    font-size: 0.88rem;
    line-height: 1.5;
}

.ai-chat-msg--user .ai-chat-bubble {
    background: var(--c-accent);
    color: #fff;
    border-bottom-right-radius: 4px;
}

.ai-chat-msg--assistant .ai-chat-bubble {
    background: var(--c-bg);
    color: var(--c-text);
    border: 1px solid var(--c-border);
    border-bottom-left-radius: 4px;
}

.ai-chat-typing {
    color: var(--c-muted);
    font-style: italic;
}

.ai-chat-suggestions {
    margin-top: 1rem;
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
}

.ai-chat-chip {
    background: var(--c-bg);
    border: 1px solid var(--c-border);
    border-radius: 999px;
    padding: 0.4rem 0.8rem;
    font-size: 0.8rem;
    color: var(--c-text);
    cursor: pointer;
    transition: border-color 0.12s, color 0.12s;
}

.ai-chat-chip:hover:not(:disabled) {
    border-color: var(--c-accent);
    color: var(--c-accent);
}

.ai-chat-input {
    margin-top: 0.9rem;
    display: flex;
    gap: 0.6rem;
}

.ai-chat-input input {
    flex: 1;
    padding: 0.6rem 0.85rem;
    border: 1.5px solid var(--c-border);
    border-radius: 9px;
    font-size: 0.88rem;
    font-family: inherit;
    color: var(--c-text);
}

.ai-chat-input input:focus {
    outline: none;
    border-color: var(--c-accent);
}

/* Reorder table */
.ai-reorder-note {
    margin: 0 0 0.6rem;
    font-size: 0.78rem;
    color: #b45309;
}

.ai-reorder-table-wrap {
    overflow-x: auto;
    margin-top: 0.5rem;
}

.ai-reorder-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.85rem;
}

.ai-reorder-table th,
.ai-reorder-table td {
    text-align: left;
    padding: 0.5rem 0.7rem;
    border-bottom: 1px solid var(--c-border);
    white-space: nowrap;
}

.ai-reorder-table th {
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--c-muted);
}

.ai-reorder-table .num {
    text-align: right;
}

.days-pill {
    display: inline-block;
    min-width: 2.2rem;
    text-align: center;
    padding: 0.1rem 0.45rem;
    border-radius: 999px;
    font-size: 0.78rem;
    font-weight: 600;
}

.days-pill--crit {
    background: #fef2f2;
    color: #b91c1c;
}

.days-pill--warn {
    background: #fffbeb;
    color: #b45309;
}

.days-pill--ok {
    background: #f0fdf4;
    color: #15803d;
}
</style>
